staff_managerment/config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  #     resources :admins

  #     root to: "admins#index"
  #   end
  devise_for :admins, :skip => [:sessions]

  as :admin do
    get 'admins/sign_in' => 'devise/sessions#new', :as => :new_admin_session
    post 'sessions/admin' => 'devise/sessions#create', :as => :admin_session
    delete 'admins/sign_out' => 'devise/sessions#destroy', :as => :destroy_admin_session
  end
  get 'sessions/new'
  resources :acounts
  #resources :staffs
  resources :staff_skills
  resources :skills
  resources :positions
  resources :projects
  resources :framworks
  resources :teams
  resources :sessions 
  resources :staffs, :path => "information"

  root 'skills#page_home'
  # get    '/login' => 'sessions#new'
  # post   '/login' => 'sessions#create'
  # delete '/logout' => 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # admin skill (add)
  get '/skill' => 'skills#index'
  get '/skill/1' => 'skills#show'
  post '/skill/new' => 'skills#create'
  post '/skill/1/edit' => 'skills#edit'

  get '/project' => 'projects#index'
  get '/project/1' => 'projects#show'
  post '/project/new' => 'projects#create'
  post '/project/1/edit' => 'projects#edit'

  get '/team' => 'teams#index'
  get '/team/1' => 'teams#show'
  post '/team/new' => 'teams#create'
  post '/team/1/edit' => 'teams#edit'

  get '/position' => 'positions#index'
  get '/position/1' => 'teapositionsms#show'
  post '/position/new' => 'positions#create'
  post '/position/1/edit' => 'positions#edit'

  get '/framwork' => 'framworks#index'
  get '/framwork/1' => 'framworks#show'
  post '/framwork/new' => 'framworks#create'
  post '/framwork/1/edit' => 'framworks#edit'

  #get '/staff' => 'staffs#index'
  get '/information/1' => 'staffs#show'
  post '/information/new' => 'staffs#create'
  post '/information/1/edit' => 'staffs#edit'
  get '/information' => 'staffs#page_home'
  post '/information' => 'staffs#search'
  #get '/staff/1/detail' => 'staffs#detail'

  get '/staff_skill' => 'staff_skills#index'
  get '/staff_skill/1' => 'staff_skills#show'
  post '/staff_skill/new' => 'staff_skills#create'
  post '/staff_skill/1/edit' => 'staff_skills#edit'

 
end

staff_managerment/app/models/framwork.rb
class Framwork < ApplicationRecord
	validates_presence_of :name
	has_many :project
end

staff_managerment/app/controllers/framworks_controller.rb
class FramworksController < ApplicationController
  before_action :set_framwork, only: [:show, :edit, :update, :destroy]
before_action :authenticate_admin!, only: [:edit, :update, :destroy, :new]
  # GET /framworks
  # GET /framworks.json
  def index
    @framworks = Framwork.all
  end

  # GET /framworks/1
  # GET /framworks/1.json
  def show
  end

  # GET /framworks/new
  def new
    @framwork = Framwork.new
  end

  # GET /framworks/1/edit
  def edit
  end

  # POST /framworks
  # POST /framworks.json
  def create
    @framwork = Framwork.new(framwork_params)

    respond_to do |format|
      if @framwork.save
        format.html { redirect_to @framwork, notice: 'Framwork was successfully created.' }
        format.json { render :show, status: :created, location: @framwork }
      else
        format.html { render :new }
        format.json { render json: @framwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /framworks/1
  # PATCH/PUT /framworks/1.json
  def update
    respond_to do |format|
      if @framwork.update(framwork_params)
        format.html { redirect_to @framwork, notice: 'Framwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @framwork }
      else
        format.html { render :edit }
        format.json { render json: @framwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /framworks/1
  # DELETE /framworks/1.json
  def destroy
    @framwork.destroy
    respond_to do |format|
      format.html { redirect_to framworks_url, notice: 'Framwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_framwork
      @framwork = Framwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def framwork_params
      params.require(:framwork).permit(:name)
    end
end

staff_managerment/app/helpers/framworks_helper.rb
module FramworksHelper
end

staff_managerment/app/views/framworks/_form.html.erb
<%= form_with(model: framwork, local: true) do |form| %>
  <% if framwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(framwork.errors.count, "error") %> prohibited this framwork from being saved:</h2>

      <ul>
        <% framwork.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

staff_managerment/app/views/framworks/edit.html.erb
<h1>Editing Framwork</h1>

<%= render 'form', framwork: @framwork %>

<%= link_to 'Show', @framwork %> |
<%= link_to 'Back', framworks_path %>

staff_managerment/app/views/framworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Framworks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @framworks.each do |framwork| %>
      <tr>
        <td><%= framwork.name %></td>
        <td><%= link_to 'Show', framwork %></td>
        <td><%= link_to 'Edit', edit_framwork_path(framwork) %></td>
        <td><%= link_to 'Destroy', framwork, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Framwork', new_framwork_path %>

staff_managerment/app/views/framworks/new.html.erb
<h1>New Framwork</h1>

<%= render 'form', framwork: @framwork %>

<%= link_to 'Back', framworks_path %>

staff_managerment/app/views/framworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @framwork.name %>
</p>

<%= link_to 'Edit', edit_framwork_path(@framwork) %> |
<%= link_to 'Back', framworks_path %>