staff_managerment/config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  #     resources :admins

  #     root to: "admins#index"
  #   end
  devise_for :admins, :skip => [:sessions]

  as :admin do
    get 'admins/sign_in' => 'devise/sessions#new', :as => :new_admin_session
    post 'sessions/admin' => 'devise/sessions#create', :as => :admin_session
    delete 'admins/sign_out' => 'devise/sessions#destroy', :as => :destroy_admin_session
  end
  get 'sessions/new'
  resources :acounts
  #resources :staffs
  resources :staff_skills
  resources :skills
  resources :positions
  resources :projects
  resources :framworks
  resources :teams
  resources :sessions 
  resources :staffs, :path => "information"

  root 'skills#page_home'
  # get    '/login' => 'sessions#new'
  # post   '/login' => 'sessions#create'
  # delete '/logout' => 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # admin skill (add)
  get '/skill' => 'skills#index'
  get '/skill/1' => 'skills#show'
  post '/skill/new' => 'skills#create'
  post '/skill/1/edit' => 'skills#edit'

  get '/project' => 'projects#index'
  get '/project/1' => 'projects#show'
  post '/project/new' => 'projects#create'
  post '/project/1/edit' => 'projects#edit'

  get '/team' => 'teams#index'
  get '/team/1' => 'teams#show'
  post '/team/new' => 'teams#create'
  post '/team/1/edit' => 'teams#edit'

  get '/position' => 'positions#index'
  get '/position/1' => 'teapositionsms#show'
  post '/position/new' => 'positions#create'
  post '/position/1/edit' => 'positions#edit'

  get '/framwork' => 'framworks#index'
  get '/framwork/1' => 'framworks#show'
  post '/framwork/new' => 'framworks#create'
  post '/framwork/1/edit' => 'framworks#edit'

  #get '/staff' => 'staffs#index'
  get '/information/1' => 'staffs#show'
  post '/information/new' => 'staffs#create'
  post '/information/1/edit' => 'staffs#edit'
  get '/information' => 'staffs#page_home'
  post '/information' => 'staffs#search'
  #get '/staff/1/detail' => 'staffs#detail'

  get '/staff_skill' => 'staff_skills#index'
  get '/staff_skill/1' => 'staff_skills#show'
  post '/staff_skill/new' => 'staff_skills#create'
  post '/staff_skill/1/edit' => 'staff_skills#edit'

 
end

staff_managerment/app/models/acount.rb
class Acount < ApplicationRecord
	validates_presence_of :username, :password
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

staff_managerment/app/controllers/acounts_controller.rb
class AcountsController < ApplicationController
  before_action :set_acount, only: [:show, :edit, :update, :destroy]
before_action :authenticate_admin!, only: [:edit, :update, :destroy, :new]
  # GET /acounts
  # GET /acounts.json
  def index
    @acounts = Acount.all
  end

  # GET /acounts/1
  # GET /acounts/1.json
  def show
  end

  # GET /acounts/new
  def new
    @acount = Acount.new
  end

  # GET /acounts/1/edit
  def edit
  end

  # POST /acounts
  # POST /acounts.json
  def create
    @acount = Acount.new(acount_params)

    respond_to do |format|
      if @acount.save
        format.html { redirect_to @acount, notice: 'Acount was successfully created.' }
        format.json { render :show, status: :created, location: @acount }
      else
        format.html { render :new }
        format.json { render json: @acount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acounts/1
  # PATCH/PUT /acounts/1.json
  def update
    respond_to do |format|
      if @acount.update(acount_params)
        format.html { redirect_to @acount, notice: 'Acount was successfully updated.' }
        format.json { render :show, status: :ok, location: @acount }
      else
        format.html { render :edit }
        format.json { render json: @acount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acounts/1
  # DELETE /acounts/1.json
  def destroy
    @acount.destroy
    respond_to do |format|
      format.html { redirect_to acounts_url, notice: 'Acount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acount
      @acount = Acount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acount_params
      params.require(:acount).permit(:username, :password)
    end
end

staff_managerment/app/helpers/acounts_helper.rb
module AcountsHelper
end

staff_managerment/app/views/acounts/_form.html.erb
<%= form_with(model: acount, local: true) do |form| %>
  <% if acount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(acount.errors.count, "error") %> prohibited this acount from being saved:</h2>

      <ul>
        <% acount.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

staff_managerment/app/views/acounts/edit.html.erb
<h1>Editing Acount</h1>

<%= render 'form', acount: @acount %>

<%= link_to 'Show', @acount %> |
<%= link_to 'Back', acounts_path %>

staff_managerment/app/views/acounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Acounts</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acounts.each do |acount| %>
      <tr>
        <td><%= acount.username %></td>
        <td><%= acount.password %></td>
        <td><%= link_to 'Show', acount %></td>
        <td><%= link_to 'Edit', edit_acount_path(acount) %></td>
        <td><%= link_to 'Destroy', acount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acount', new_acount_path %>

staff_managerment/app/views/acounts/new.html.erb
<h1>New Acount</h1>

<%= render 'form', acount: @acount %>

<%= link_to 'Back', acounts_path %>

staff_managerment/app/views/acounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @acount.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @acount.password %>
</p>

<%= link_to 'Edit', edit_acount_path(@acount) %> |
<%= link_to 'Back', acounts_path %>