staff_managerment/config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  #     resources :admins

  #     root to: "admins#index"
  #   end
  devise_for :admins, :skip => [:sessions]

  as :admin do
    get 'admins/sign_in' => 'devise/sessions#new', :as => :new_admin_session
    post 'sessions/admin' => 'devise/sessions#create', :as => :admin_session
    delete 'admins/sign_out' => 'devise/sessions#destroy', :as => :destroy_admin_session
  end
  get 'sessions/new'
  resources :acounts
  #resources :staffs
  resources :staff_skills
  resources :skills
  resources :positions
  resources :projects
  resources :framworks
  resources :teams
  resources :sessions 
  resources :staffs, :path => "information"

  root 'skills#page_home'
  # get    '/login' => 'sessions#new'
  # post   '/login' => 'sessions#create'
  # delete '/logout' => 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # admin skill (add)
  get '/skill' => 'skills#index'
  get '/skill/1' => 'skills#show'
  post '/skill/new' => 'skills#create'
  post '/skill/1/edit' => 'skills#edit'

  get '/project' => 'projects#index'
  get '/project/1' => 'projects#show'
  post '/project/new' => 'projects#create'
  post '/project/1/edit' => 'projects#edit'

  get '/team' => 'teams#index'
  get '/team/1' => 'teams#show'
  post '/team/new' => 'teams#create'
  post '/team/1/edit' => 'teams#edit'

  get '/position' => 'positions#index'
  get '/position/1' => 'teapositionsms#show'
  post '/position/new' => 'positions#create'
  post '/position/1/edit' => 'positions#edit'

  get '/framwork' => 'framworks#index'
  get '/framwork/1' => 'framworks#show'
  post '/framwork/new' => 'framworks#create'
  post '/framwork/1/edit' => 'framworks#edit'

  #get '/staff' => 'staffs#index'
  get '/information/1' => 'staffs#show'
  post '/information/new' => 'staffs#create'
  post '/information/1/edit' => 'staffs#edit'
  get '/information' => 'staffs#page_home'
  post '/information' => 'staffs#search'
  #get '/staff/1/detail' => 'staffs#detail'

  get '/staff_skill' => 'staff_skills#index'
  get '/staff_skill/1' => 'staff_skills#show'
  post '/staff_skill/new' => 'staff_skills#create'
  post '/staff_skill/1/edit' => 'staff_skills#edit'

 
end

staff_managerment/app/models/project.rb
class Project < ApplicationRecord
	validates_presence_of :name
	has_one :framwork
	has_one :team
end

staff_managerment/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
before_action :authenticate_admin!, only: [:edit, :update, :destroy, :new]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :team_id, :framwork_id)
    end
end

staff_managerment/app/helpers/projects_helper.rb
module ProjectsHelper
end

staff_managerment/app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id %>
  </div>

  <div class="field">
    <%= form.label :framwork_id %>
    <%= form.number_field :framwork_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

staff_managerment/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

staff_managerment/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th>Framwork</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.team_id %></td>
        <td><%= project.framwork_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

staff_managerment/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

staff_managerment/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @project.team_id %>
</p>

<p>
  <strong>Framwork:</strong>
  <%= @project.framwork_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>