staff_managerment/config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  #     resources :admins

  #     root to: "admins#index"
  #   end
  devise_for :admins, :skip => [:sessions]

  as :admin do
    get 'admins/sign_in' => 'devise/sessions#new', :as => :new_admin_session
    post 'sessions/admin' => 'devise/sessions#create', :as => :admin_session
    delete 'admins/sign_out' => 'devise/sessions#destroy', :as => :destroy_admin_session
  end
  get 'sessions/new'
  resources :acounts
  #resources :staffs
  resources :staff_skills
  resources :skills
  resources :positions
  resources :projects
  resources :framworks
  resources :teams
  resources :sessions 
  resources :staffs, :path => "information"

  root 'skills#page_home'
  # get    '/login' => 'sessions#new'
  # post   '/login' => 'sessions#create'
  # delete '/logout' => 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # admin skill (add)
  get '/skill' => 'skills#index'
  get '/skill/1' => 'skills#show'
  post '/skill/new' => 'skills#create'
  post '/skill/1/edit' => 'skills#edit'

  get '/project' => 'projects#index'
  get '/project/1' => 'projects#show'
  post '/project/new' => 'projects#create'
  post '/project/1/edit' => 'projects#edit'

  get '/team' => 'teams#index'
  get '/team/1' => 'teams#show'
  post '/team/new' => 'teams#create'
  post '/team/1/edit' => 'teams#edit'

  get '/position' => 'positions#index'
  get '/position/1' => 'teapositionsms#show'
  post '/position/new' => 'positions#create'
  post '/position/1/edit' => 'positions#edit'

  get '/framwork' => 'framworks#index'
  get '/framwork/1' => 'framworks#show'
  post '/framwork/new' => 'framworks#create'
  post '/framwork/1/edit' => 'framworks#edit'

  #get '/staff' => 'staffs#index'
  get '/information/1' => 'staffs#show'
  post '/information/new' => 'staffs#create'
  post '/information/1/edit' => 'staffs#edit'
  get '/information' => 'staffs#page_home'
  post '/information' => 'staffs#search'
  #get '/staff/1/detail' => 'staffs#detail'

  get '/staff_skill' => 'staff_skills#index'
  get '/staff_skill/1' => 'staff_skills#show'
  post '/staff_skill/new' => 'staff_skills#create'
  post '/staff_skill/1/edit' => 'staff_skills#edit'

 
end

staff_managerment/app/models/acount.rb
class Acount < ApplicationRecord
	validates_presence_of :username, :password
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

staff_managerment/app/models/admin.rb
class Admin < ApplicationRecord
	# self.table_name = "admin"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

staff_managerment/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

staff_managerment/app/models/framwork.rb
class Framwork < ApplicationRecord
	validates_presence_of :name
	has_many :project
end

staff_managerment/app/models/position.rb
class Position < ApplicationRecord
	validates_presence_of :name
	has_many :staff
end

staff_managerment/app/models/project.rb
class Project < ApplicationRecord
	validates_presence_of :name
	has_one :framwork
	has_one :team
end

staff_managerment/app/models/skill.rb
class Skill < ApplicationRecord
	validates_presence_of :name
	has_one :staff
end

staff_managerment/app/models/staff.rb
class Staff < ApplicationRecord
	mount_uploader :picture, PictureUploader
	validates_presence_of :name, :email, :phone, :gender, :address, :team_id, :image, :introduction, :feeling, :position_id
	has_one :team
	has_one :position
	has_one :staff_skill
	#include SearchCop
	# def self.search(search)
 #  		if search
 #    		where('name LIKE ?', "%#{search}%")
 #  		else
 #    		scoped
 #  		end
	# end

	# search_scope :search do
 #    attributes all: [:name]  #khai báo tập các field muốn search

 #    options :all, type: :fulltext, default: true #định nghĩa chúng ta muốn sử dụng full-text search
 #  end
end

staff_managerment/app/models/staff_skill.rb
class StaffSkill < ApplicationRecord
	validates_presence_of :staff_id, :skill_id
	has_many :staff
	has_many :skill
end

staff_managerment/app/models/team.rb
class Team < ApplicationRecord
	validates_presence_of :name
	has_many :project
	has_many :staff
end

staff_managerment/app/helpers/acounts_helper.rb
module AcountsHelper
end

staff_managerment/app/helpers/application_helper.rb
module ApplicationHelper
	# def sortable(column, title = nil)
	#   title ||= column.titleize
	#   css_class = column == sort_column ? "current #{sort_direction}" : nil
	#   direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	#   link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	# end
end

staff_managerment/app/helpers/framworks_helper.rb
module FramworksHelper
end

staff_managerment/app/helpers/positions_helper.rb
module PositionsHelper
end

staff_managerment/app/helpers/projects_helper.rb
module ProjectsHelper
end

staff_managerment/app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(acount)
    	session[:username] = acount.username
    end

	def current_user
	    if session[:username]
	      @current_user ||= Acount.find_by(username: session[:username])
	    end
  	end

  # Returns true if the user is logged in, false otherwise.
    def logged_in?
    	!current_user.nil?
    end

    def log_out
    	session.delete(:username)
    	@current_user = nil
  	end
end

staff_managerment/app/helpers/skills_helper.rb
module SkillsHelper
end

staff_managerment/app/helpers/staff_skills_helper.rb
module StaffSkillsHelper
end

staff_managerment/app/helpers/staffs_helper.rb
module StaffsHelper
end

staff_managerment/app/helpers/teams_helper.rb
module TeamsHelper
end

staff_managerment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <base href="assets">
    <title>StaffManagerment</title>
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag 'home_page', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" href="home_page.css" rel="stylesheet">
    <!-- <link rel="stylesheet" type="text/css" href="imagehover.css" rel="stylesheet"> -->

    
  </head>

<body id="background">  
    <p class="notice" style="color: red"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-5">
                    <!-- Brand -->
                    <nav class="navbar navbar-expand-sm">
                        
                        <div class="navbar-brand"><%= link_to 'Home', root_url %></div>
                    </nav>
            </div>
            <!-- List Menu -->
            <div class="col-md-7 ">
                <div class="row">
                        <div class="col-md-3">
                            <nav class="navbar navbar-expand-sm">
                                <!-- Links -->
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <div class="nav-link"><%= link_to 'Information', staffs_path %></div>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                   
                        <div class="col-md-3">
                            <nav class="navbar navbar-expand-sm">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                       <%= link_to 'Team', teams_path, :class => 'nav-link' %>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        
                        <% if admin_signed_in? %>
                       
                        <div class="col-md-3">
                            <nav class="navbar navbar-expand-sm">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <%= link_to 'Edit Acount', edit_admin_registration_path, :class => 'nav-link' %>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="col-md-3">
                            <nav class="navbar navbar-expand-sm">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'nav-link'  %>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <% else %>
                        <div class="col-md-3">
                            <nav class="navbar navbar-expand-sm">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                    <%= link_to "Sign up", new_admin_registration_path, :class => 'nav-link'  %>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="col-md-3">
                            <nav class="navbar navbar-expand-sm">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                       <%= link_to "Signin", new_admin_session_path, :class => 'navbar-link'  %>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <% end %>
                </div>
            </div>
        </div>
            <%#= render "staffs/form" %>
        <%= yield %>     
    </div>   
   
</body>

</html>

staff_managerment/app/views/layouts/page_detail.html.erb
<html>
<body>
    <div class="container-fluid" id="background">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-5">
                    <!-- Brand -->
                    <nav class="navbar navbar-expand-sm"><a class="navbar-brand" href="#">HOME</a></nav>
                </div>
            </div>
            <br>
        </div>
        <!-- Header -->
        <div class="container-fluid">
            <div class="row">
            	<div class="col-md-2"></div>
            	<div class="col-md-8 col-md-offset-2">
            		<div class="row">
            			<div class="col-sm-4">
                    <h2>About Me: </h2>
                    <div class="detail_image">
                       <img class="thum_image" src="<%= image_url '3.jpg' %>" alt="Image" width="100%" height="400px;">
                    </div>
                    <h3>Name: 	</h3>
                    <h3>Gender: </h3>
                    <h3>Position: </h3>
                    <h3>Team: </h3>
                    <!-- <ul class="nav nav-pills flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">Active</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                    </ul> -->
                    <hr class="d-sm-none">
                </div>
                <!-- Sidebar -->
                <br><br>
                <div class="col-sm-8">
                		<h2>Introduction</h2>
                		<p>A revolution in resolution. Sharp and clear photos with the world's best photo engine, incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquipex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
                		<br>
                		<h2>My Feeling</h2>
                		<p>A revolution in resolution. Sharp and clear photos with the world's best photo engine, incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquipex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
                		<br><br>
                    <h2>PROJECT</h2>
                    <p>Projects I did:</p>
                    <table>
                        <tr>
                            <th>Name</th>
                            <th>Team</th>
                            <th>Framework</th>
                        </tr>
                        <tr>
                            <td>Jill</td>
                            <td>Smith</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>Eve</td>
                            <td>Jackson</td>
                            <td>94</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                        </tr>
                    </table>
                    <br><br>
                    <h2></h2>
                </div>
                <!-- Content -->
            		</div>
            	</div>
            </div>
        </div>
    </div>
</body>

</html>

staff_managerment/app/views/layouts/page_overview.html.erb
<html>

<body>
    <div class="container-fluid" id="background">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-5">
                    <!-- Brand -->
                    <nav class="navbar navbar-expand-sm"><a class="navbar-brand" href="#">HOME</a></nav>
                </div>
                <!-- List Menu -->
                <div class="col-md-6 ">
                    <div class="row">
                        <div class="col-md-3">
                            <nav class="navbar navbar-expand-sm">
                                <!-- Links -->
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Information</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="col-md-3">
                            <nav class="navbar navbar-expand-sm">
                                <!-- Links -->
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">About Us</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="col-md-2">
                            <nav class="navbar navbar-expand-sm">
                                <!-- Links -->
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Team</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <div class="col-md-3">
                            <nav class="navbar navbar-expand-sm">
                                <!-- Links -->
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Contact Us</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <!-- Header -->
        <div class="row">
            <div class="col-md-8"></div>
            <div class="col-md-3 col-md-offset-4">
                <div class="input-group">
                    <span class="input-group-prepend">
                        <div class="input-group-text bg-transparent border-right-0">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                    <input class="form-control py-2 border-left-0 border" type="search" value="..." id="example-search-input" />
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button">
                            Search
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <!-- Search -->
        <!--         <div class="container-fluid">
        	<div class="row">
        	<div class="col-md-5 fakeimg_content">
						<div class="row">
							<div class="col-md-5">
								<div class="thum_image">
									<img class="thum_image" src="<%= image_url '3.jpg' %>" alt="Image">
								</div>
								<button type="button" class="btn btn-warning fakeing_button">Details</button>
							</div>
							<div class="col-md-7">
								<h2>Name: </h2>
								<div class="fakeing_line"></div>
								<h2>Gender: </h2>
								<div class="fakeing_line"></div>
								<h2>Position: </h2>
								<div class="fakeing_line"></div>
							</div>
						</div>
        	</div>

					<div class="col-md-2"></div>

        	<div class="col-md-5 fakeimg_content">
        		<div class="row">
							<div class="col-md-5">
								<div class="thum_image">
									<img class="thum_image" src="<%= image_url '3.jpg' %>" alt="Image">
								</div>
								<button type="button" class="btn btn-warning fakeing_button">Details</button>
							</div>
							<div class="col-md-7">
								<h2>Name: </h2>
								<div class="fakeing_line"></div>
								<h2>Gender: </h2>
								<div class="fakeing_line"></div>
								<h2>Position: </h2>
								<div class="fakeing_line"></div>
							</div>
						</div>
        	</div>
        </div>
        </div>

        <div class="container-fluid">
        	<div class="row">
        	<div class="col-md-5 fakeimg_content">
						<div class="row">
							<div class="col-md-5">
								<div class="thum_image">
									<img class="thum_image" src="<%= image_url '1.jpg' %>" alt="Image">
								</div>
								<button type="button" class="btn btn-warning fakeing_button">Details</button>
							</div>
							<div class="col-md-7">
								<h2>Name: </h2>
								<div class="fakeing_line"></div>
								<h2>Gender: </h2>
								<div class="fakeing_line"></div>
								<h2>Position: </h2>
								<div class="fakeing_line"></div>
							</div>
						</div>
        	</div>

					<div class="col-md-2"></div>

        	<div class="col-md-5 fakeimg_content">
        		<div class="row">
							<div class="col-md-5">
								<div class="thum_image">
									<img class="thum_image" src="<%= image_url '2.jpg' %>" alt="Image">
								</div>
								<button type="button" class="btn btn-warning fakeing_button">Details</button>
							</div>
							<div class="col-md-7">
								<h2>Name: </h2>
								<div class="fakeing_line"></div>
								<h2>Gender: </h2>
								<div class="fakeing_line"></div>
								<h2>Position: </h2>
								<div class="fakeing_line"></div>
							</div>
						</div>
        	</div>
        </div>
        </div> -->
        <div class="container-fluid" id="content_container">
            <h1>People</h1>
            <br>
        </div>
        <div class="container-fluid" id="content_container">
            <div class="row">
                <div class="col-xl-3">
                    <img class="content_image" src="<%= image_url '1.jpg' %>" alt="Image">
                    <h2 style="color: #A52A2A; padding-left: 15px; padding-top: 15px; text-align: center; font: 38px Lora Arial">Đàm Thiên Phúc</h2>
                    <h3 style="color:	#0000CD; padding-top: 5px; text-align: center; font: 28px Lora Arial">Web Developer</h3>
                    <br>
                    <h6 style="color: black; text-align: center;">In many countries, a mayor is the highest-ranking official in a government.</h6>
                    <br>
                    <div class="row">
                    </div>
                </div>
                <div class="col-xl-3">
                    <img class="content_image" src="<%= image_url '3.jpg' %>" alt="Image">
                    <h2 style="color: #A52A2A; padding-left: 15px; padding-top: 15px; text-align: center; font: 38px Lora Arial">Đàm Thiên Phúc</h2>
                    <h3 style="color: #0000CD;padding-top: 5px; text-align: center; font: 28px Lora Arial">Web Developer</h3>
                    <br>
                    <h6 style="color: black; text-align: center;">In many countries, a mayor is the highest-ranking official in a government.</h6>
                    <br>
                    <div class="row">
                    </div>
                </div>
                <div class="col-xl-3">
                    <img class="content_image" src="<%= image_url '4.jpg' %>" alt="Image">
                    <h2 style="color: #A52A2A; padding-left: 15px; padding-top: 15px; text-align: center; font: 38px Lora Arial">Đàm Thiên Phúc</h2>
                    <h3 style="color: #0000CD;padding-top: 5px; text-align: center; font: 28px Lora Arial">Web Developer</h3><br>
                    <h6 style="color: black; text-align: center;">In many countries, a mayor is the highest-ranking official in a government.</h6>
                    <br>
                    <div class="row">
                    </div>
                </div>
                <div class="col-xl-3">
                    <img class="content_image" src="<%= image_url '5.jpg' %>" alt="Image">
                    <h2 style="color: #A52A2A; padding-left: 15px; padding-top: 15px; text-align: center; font: 38px Lora Arial">Đàm Thiên Phúc</h2>
                    <h3 style="color: #0000CD;padding-top: 5px; text-align: center; font: 28px Lora Arial">Web Developer</h3><br>
                    <h6 style="color: black; text-align: center;">In many countries, a mayor is the highest-ranking official in a government.</h6>
                    <br>
                    <div class="row">
                    </div>
                    <br>
                </div>
            </div>
        </div>
        <br>
        <div class="container-fluid" id="content_container">
            <div class="row">
                <div class="col-xl-3">
                    <img class="content_image" src="<%= image_url '4.jpg' %>" alt="Image">
                    <h2 style="color: #A52A2A; padding-left: 15px; padding-top: 15px; text-align: center; font: 38px Lora Arial">Đàm Thiên Phúc</h2>
                    <h3 style="color:	#0000CD; padding-top: 5px; text-align: center; font: 28px Lora Arial">Web Developer</h3>
                    <br>
                    <h6 style="color: black; text-align: center;">In many countries, a mayor is the highest-ranking official in a government.</h6>
                    <br>
                    <div class="row">
                    </div>
                </div>
                <div class="col-xl-3">
                    <img class="content_image" src="<%= image_url '5.jpg' %>" alt="Image">
                    <h2 style="color: #A52A2A; padding-left: 15px; padding-top: 15px; text-align: center; font: 38px Lora Arial">Đàm Thiên Phúc</h2>
                    <h3 style="color: #0000CD;padding-top: 5px; text-align: center; font: 28px Lora Arial">Web Developer</h3>
                    <br>
                    <h6 style="color: black; text-align: center;">In many countries, a mayor is the highest-ranking official in a government.</h6>
                    <br>
                    <div class="row">
                    </div>
                </div>
                <div class="col-xl-3">
                    <img class="content_image" src="<%= image_url '3.jpg' %>" alt="Image">
                    <h2 style="color: #A52A2A; padding-left: 15px; padding-top: 15px; text-align: center; font: 38px Lora Arial">Đàm Thiên Phúc</h2>
                    <h3 style="color: #0000CD;padding-top: 5px; text-align: center; font: 28px Lora Arial">Web Developer</h3><br>
                    <h6 style="color: black; text-align: center;">In many countries, a mayor is the highest-ranking official in a government.</h6>
                    <br>
                    <div class="row">
                    </div>
                </div>
                <div class="col-xl-3">
                    <img class="content_image" src="<%= image_url '1.jpg' %>" alt="Image">
                    <h2 style="color: #A52A2A; padding-left: 15px; padding-top: 15px; text-align: center; font: 38px Lora Arial">Đàm Thiên Phúc</h2>
                    <h3 style="color: #0000CD;padding-top: 5px; text-align: center; font: 28px Lora Arial">Web Developer</h3><br>
                    <h6 style="color: black; text-align: center;">In many countries, a mayor is the highest-ranking official in a government.</h6>
                    <br>
                    <div class="row">
                    </div>
                    <br>
                </div>
            </div>
        </div>
        <br>
    </div>
</body>

</html>

staff_managerment/app/views/shared/_error_messages.html.erb
<% if @acount.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@acount.errors.count, "error") %>.
    </div>
    <ul>
    <% @acount.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>